name: CI

on:
  push:
    paths:
      - 'impl/**'
    branches:
      - "main"
  pull_request:
    paths:
      - 'impl/**'
    branches:
      - "main"

# required for publication of test results
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12.6"]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install project requirements
        run: pip install -r requirements.txt
        working-directory: impl
      - name: Run tests
        run: pytest -v --forked --junitxml=test-result.xml
      - name: Publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-result.xml
          check_name: Test Result (Python ${{matrix.python-version}})

